// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9XJNwlOKglTVZchGWFxeaMr2GDMoFwT4',
    appId: '1:1044150413123:web:33f46223f6944b2b5e71f6',
    messagingSenderId: '1044150413123',
    projectId: 'flutter-chat-app-537f2',
    authDomain: 'flutter-chat-app-537f2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-537f2.firebasestorage.app',
    measurementId: 'G-T1CLK8FMSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJwTXaOnXIGJfN7gadOuJplaIfLHIohww',
    appId: '1:1044150413123:android:691df930e3d389df5e71f6',
    messagingSenderId: '1044150413123',
    projectId: 'flutter-chat-app-537f2',
    storageBucket: 'flutter-chat-app-537f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH31KI4yma1Xp4fWHDM-MV6NPhvN7M_Pw',
    appId: '1:1044150413123:ios:f0d99a9b6d2175b05e71f6',
    messagingSenderId: '1044150413123',
    projectId: 'flutter-chat-app-537f2',
    storageBucket: 'flutter-chat-app-537f2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH31KI4yma1Xp4fWHDM-MV6NPhvN7M_Pw',
    appId: '1:1044150413123:ios:f0d99a9b6d2175b05e71f6',
    messagingSenderId: '1044150413123',
    projectId: 'flutter-chat-app-537f2',
    storageBucket: 'flutter-chat-app-537f2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9XJNwlOKglTVZchGWFxeaMr2GDMoFwT4',
    appId: '1:1044150413123:web:a6531bd42d4a3b8a5e71f6',
    messagingSenderId: '1044150413123',
    projectId: 'flutter-chat-app-537f2',
    authDomain: 'flutter-chat-app-537f2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-537f2.firebasestorage.app',
    measurementId: 'G-N3XD3NTQ67',
  );
}
